class PopulaCursos < ActiveRecord::Migration[5.0]
  def change
    cursos = []

    cursos.push('Agronomia (ou Engenharia agronômica)',
                 'Agroecologia',
                 'Aquicultura',
                 'Tecnologia da Informação',
                 'Análise e desenvolvimento de sistemas',
                 'Análise de sistemas',
                 'Astronomia',
                 'Automação industrial (tecnologia)',
                 'Bioengenharia',
                 'Biotecnologia',
                 'Biocombustíveis',
                 'Ciências exatas (licenciatura)',
                 'Ciências moleculares (ou biomoleculares)',
                 'Ciências naturais',
                 'Computação (licenciatura)',
                 'Computação científica',
                 'Construção civil (ou engenharia civil [tecnologia])',
                 'Ciência e Tecnologia',
                 'Eletrônica',
                 'Engenharia aeroespacial',
                 'Engenharia aeronáutica',
                 'Engenharia agrícola',
                 'Engenharia de agrimensura',
                 'Engenharia de alimentos',
                 'Engenharia de áudio',
                 'Engenharia urbana',
                 'Engenharia biofísica',
                 'Engenharia biomédica',
                 'Engenharia cartográfica',
                 'Engenharia de computação',
                 'Engenharia de controle e automação',
                 'Engenharia econômica',
                 'Engenharia elétrica (ou engenharia de energia )',
                 'Engenharia eletrônica',
                 'Engenharia estrutural',
                 'Engenharia física',
                 'Engenharia florestal[9]',
                 'Prospecção geofísica',
                 'Engenharia geográfica',
                 'Engenharia geológica',
                 'Engenharia hidráulica',
                 'Engenharia humana',
                 'Engenharia industrial',
                 'Engenharia industrial madeireira',
                 'Engenharia de informação',
                 'Engenharia de instrumentação',
                 'Engenharia de instrumentação (ou Engenharia de controle e automação ou robótica)',
                 'Engenharia de manufatura',
                 'Engenharia de manutenção',
                 'Engenharia de materiais',
                 'Engenharia mecânica',
                 'Engenharia mecatrônica',
                 'Engenharia metalúrgica',
                 'Engenharia militar',
                 'Engenharia multimídia',
                 'Engenharia de minas',
                 'Engenharia naval e oceânica',
                 'Engenharia nuclear',
                 'Engenharia óptica',
                 'Engenharia de pesca',
                 'Engenharia de petróleo',
                 'Engenharia de produção',
                 'Engenharia da qualidade',
                 'Engenharia química',
                 'Engenharia sanitária',
                 'Engenharia de serviços',
                 'Engenharia de sistemas',
                 'Engenharia de sistemas eletrônicos',
                 'Engenharia de software',
                 'Engenharia de tecidos',
                 'Engenharia de telecomunicações',
                 'Engenharia têxtil',
                 'Engenharia de transportes e logística',
                 'Eletrônica embarcada (ou Autotrônica [tecnologia])',
                 'Farmacêutica (ou Farmácia ou ainda Bioquímica)',
                 'Física',
                 'Física biológica',
                 'Física computacional',
                 'Física médica',
                 'Geociências (ou ciências da terra)',
                 'Geofísica',
                 'Geologia',
                 'Informática (ou ciência da computação)',
                 'Informática biomédica',
                 'Química',
                 'Transporte hidroviário (ou transporte marítimo)',
                 'Manutenção industrial (tecnologia)',
                 'Matemática',
                 'Matemática aplicada',
                 'Matemática computacional',
                 'Ciência dos materiais (tecnologia)',
                 'Mecânica - processos de produção (tecnologia)',
                 'Mecânica de precisão (ou Mecatrônica [tecnologia])',
                 'Metalurgia (tecnologia)',
                 'Meteorologia',
                 'Oceanografia (ou oceanologia ou ainda Ciência dos Mares)',
                 'Processos gerenciais (tecnologia)',
                 'Processamento de dados',
                 'Produção (tecnologia)',
                 'Produção de materiais plásticos (tecnologia)',
                 'Produção têxtil',
                 'Química ambiental',
                 'Química industrial',
                 'Saneamento (tecnologia)',
                 'Segurança da informação (tecnologia)',
                 'Sistemas de informação',
                 'Sistemas para internet (tecnologia)',
                 'Tecnologia da informação (licenciatura)',
                 'Telecomunicações',
                 'Telemática (tecnologia)',
                 'Alimentos (tecnologia)',
                 'Bioenergia sucro-alcooleira (tecnologia)',
                 'Biologia',
                 'Biologia marinha',
                 'Biomedicina',
                 'Biotecnologia',
                 'Botânica',
                 'Ciência dos alimentos',
                 'Ciências (licenciatura)',
                 'Ciências agrárias',
                 'Ciências ambientais',
                 'Ciências da atividade física (licenciatura)',
                 'Ciências biológicas (ou biologia)',
                 'Ciências do esporte',
                 'Cosmetologia e Estética ou Estética e Cosmética',
                 'Ecologia',
                 'Engenharia Ambiental',
                 'Educação física',
                 'Enfermagem',
                 'Esportes',
                 'Fisioterapia',
                 'Fonoaudiologia',
                 'Gerontologia',
                 'Medicina',
                 'Medicina veterinária',
                 'Meio ambiente e recursos hídricos (tecnologia)',
                 'Microbiologia (ou imunologia)',
                 'Nutrição',
                 'Obstetrícia',
                 'Odontologia',
                 'Radiologia (tecnologia)',
                 'Sistemas Biomédicos (tecnologia)',
                 'Silvicultura (tecnologia)',
                 'Tecnologias em saúde - oftálmica e radiológica',
                 'Terapia ocupacional',
                 'Zootecnia',
                 'Administração',
                 'Administração pública',
                 'Agronegócio (tecnologia)',
                 'Antropologia',
                 'Arqueologia',
                 'Arquitetura',
                 'Arquivologia',
                 'Artes cênicas',
                 'Artes plásticas',
                 'Artes visuais',
                 'Automação de escritório (ou secretariado [tecnologia])',
                 'Biblioteconomia',
                 'Ciências atuariais',
                 'Comércio exterior',
                 'Ciências contábeis (ou contabilidade)',
                 'Ciências econômicas (ou economia)',
                 'Ciência da informação',
                 'Ciências políticas (ou Ciências do Estado)',
                 'Ciências sociais (ou sociologia)',
                 'Cinema',
                 'Comunicação social',
                 'Cooperativismo (ou associativismo em Redes de empresas e no agronegócio [tecnologia])',
                 'Dança',
                 'Defesa e Gestão Estratégica Internacional',
                 'Design',
                 'Design de interiores',
                 'Design de moda',
                 'Desenho industrial (ou Design gráfico)',
                 'Direito',
                 'Editoração (ou produção editorial)',
                 'Educação artística',
                 'Educação musical (licenciatura)',
                 'Escultura',
                 'Estatística',
                 'Estudos literários',
                 'Eventos (tecnologia)',
                 'Fotografia (ou Gravura)',
                 'Filosofia',
                 'Gastronomia',
                 'Geografia',
                 'Gestão da Qualidade (tecnologia)',
                 'Gestão ambiental (tecnologia)]',
                 'Gestão de comércio internacional',
                 'Gestão de empresas',
                 'Gestão empresarial (tecnologia)',
                 'Gestão de políticas públicas',
                 'Gestão da produção de calçados (tecnologia)',
                 'História',
                 'História da arte',
                 'Hotelaria',
                 'Jornalismo',
                 'Lazer',
                 'Letras',
                 'Linguística',
                 'Logística (tecnologia)',
                 'Logística aeroportuária (tecnologia)',
                 'Logística e transportes (tecnologia)',
                 'Marketing (ou propaganda)',
                 'Museologia',
                 'Música',
                 'Paisagismo',
                 'Pedagogia',
                 'Pintura',
                 'Psicologia',
                 'Psicopedagogia',
                 'Publicidade',
                 'Produção Fonográfica',
                 'Radialismo (ou Rádio & TV, ou ainda Audiovisual)',
                 'Recursos humanos',
                 'Relações internacionais (ou Diplomacia)',
                 'Relações públicas',
                 'Secretariado (tecnologia)',
                 'Serviço social',
                 'Teatro',
                 'Teologia',
                 'Design de jogos digitais',
                 'Turismologia',
                 'Urbanismo',
    )

    cursos.each do |c|
      CursoSuperior.create(nome: c)
    end
  end
end
